classdef Configuration_CCL < IModelConfiguration
    %Configuration_CCL Configuration to generate the model of the
    %closed-loop continuous system
    %   Detailed explanation goes here
    properties (Constant)
        Name = ["Continuous closed-loop" "Configuration_CCL"];
        x = 30
        y = 150
        w = 30
        h = 30
        offset = 100
    end
    
    methods (Static)
        function generate(ModelName,TFPlant,TFController)
            %GENERATE Summary of this method goes here
            %   Detailed explanation goes here
            %(x,y) - top left corner of the block
            %(x+w,y+h) - lower right corner of the block
            
            %Step
            source = 'simulink/Sources/Step';
            dest = [ModelName '/Step'];
            k=0;
            add_block(source, dest,'Position',...
                [Configuration_CCL.x ...
                Configuration_CCL.y ...
                Configuration_CCL.x + Configuration_CCL.w ...
                Configuration_CCL.y + Configuration_CCL.h]);
            
            %Ramp
            source = 'simulink/Sources/Ramp';
            dest = [ModelName '/Ramp'];
            k = k + 1;
            add_block(source, dest,'Position',...
                [Configuration_CCL.x ...
                Configuration_CCL.y + k * Configuration_CCL.offset...
                Configuration_CCL.x + Configuration_CCL.w ...
                Configuration_CCL.y + k * Configuration_CCL.offset + Configuration_CCL.h]);
            
            %Integrator
            source = 'simulink/Continuous/Integrator';
            dest = [ModelName '/RampIntegrator'];
            add_block(source, dest,'Position',...
                [Configuration_CCL.x + Configuration_CCL.offset ...
                Configuration_CCL.y + Configuration_CCL.offset...
                Configuration_CCL.x + Configuration_CCL.offset + Configuration_CCL.w ...
                Configuration_CCL.y + Configuration_CCL.offset + Configuration_CCL.h]);
            
            add_line(ModelName,'Ramp/1','RampIntegrator/1',...
                'autorouting','on');
                        
            %Switch key
            source = 'simulink/Sources/Constant';
            dest = [ModelName '/SwitchKey'];
            add_block(source, dest,'Position',...
                [Configuration_CCL.x + Configuration_CCL.offset ...
                Configuration_CCL.y - Configuration_CCL.offset...
                Configuration_CCL.x + Configuration_CCL.offset + Configuration_CCL.w ...
                Configuration_CCL.y - Configuration_CCL.offset + Configuration_CCL.h]);
            
            %Multiport switch
            source = 'simulink/Signal Routing/Multiport Switch';
            dest = [ModelName '/MPSwitch'];
            k = k + 1;
            add_block(source, dest,'Position',...
                [Configuration_CCL.x + k * Configuration_CCL.offset ...
                Configuration_CCL.y ...
                Configuration_CCL.x + k * Configuration_CCL.offset + Configuration_CCL.w ...
                Configuration_CCL.y + k * Configuration_CCL.h]);
            
            add_line(ModelName,'Step/1','MPSwitch/2',...
                'autorouting','on');
            add_line(ModelName,'Ramp/1','MPSwitch/3',...
                'autorouting','on');
            add_line(ModelName,'RampIntegrator/1','MPSwitch/4',...
                'autorouting','on');
            add_line(ModelName,'SwitchKey/1','MPSwitch/1',...
                'autorouting','on');
            
            %Sum
            source = 'built-in/Sum';
            dest = [ModelName '/Discriminator'];
            k = k + 1;
            add_block(source, dest,'Position',...
                [Configuration_CCL.x + k * Configuration_CCL.offset ...
                Configuration_CCL.y ...
                Configuration_CCL.x + k * Configuration_CCL.offset + Configuration_CCL.w ...
                Configuration_CCL.y + Configuration_CCL.h]);
            set_param([ModelName '/Discriminator'],'Inputs','+-');
            
            add_line(ModelName,'MPSwitch/1','Discriminator/1',...
                'autorouting','on');
            
            %TF controller
            source = 'simulink/Continuous/Transfer Fcn';
            dest = [ModelName '/TFController'];
            k = k + 1;
            add_block(source, dest, 'Position',...
                [Configuration_CCL.x + k * Configuration_CCL.offset ...
                Configuration_CCL.y ...
                Configuration_CCL.x + k * Configuration_CCL.offset + Configuration_CCL.w ...
                Configuration_CCL.y + Configuration_CCL.h]);
            set_param(dest,'Numerator',...
                ['[' num2str(TFController.num{1}) ']']);
            set_param(dest,'Denominator',...
                ['[' num2str(TFController.den{1}) ']']);
            
            add_line(ModelName,'Discriminator/1','TFController/1',...
                'autorouting','on');
            
            %Error Scope
            source = 'simulink/Sinks/Scope';
            dest = [ModelName '/ErrorScope'];           
            add_block(source, dest, 'Position',...
                [Configuration_CCL.x + k * Configuration_CCL.offset ...
                Configuration_CCL.y - Configuration_CCL.offset...
                Configuration_CCL.x + k * Configuration_CCL.offset + Configuration_CCL.w ...
                Configuration_CCL.y - Configuration_CCL.offset + Configuration_CCL.h]);
            
            add_line(ModelName,'Discriminator/1','ErrorScope/1',...
                'autorouting','on');   
            
            %TF plant
            source = 'simulink/Continuous/Transfer Fcn';
            dest = [ModelName '/TFPlant'];
            k = k + 1;
            add_block(source, dest, 'Position',...
                [Configuration_CCL.x + k * Configuration_CCL.offset ...
                Configuration_CCL.y ...
                Configuration_CCL.x + k * Configuration_CCL.offset + Configuration_CCL.w ...
                Configuration_CCL.y + Configuration_CCL.h]);
            set_param(dest,'Numerator',...
                ['[' num2str(TFPlant.num{1}) ']']);
            set_param(dest,'Denominator',...
                ['[' num2str(TFPlant.den{1}) ']']);
            
            add_line(ModelName,'TFController/1','TFPlant/1',...
                'autorouting','on');
            
            %Out Scope
            source = 'simulink/Sinks/Scope';
            dest = [ModelName '/OutputScope'];
            k = k + 1;
            add_block(source, dest, 'Position',...
                [Configuration_CCL.x + k * Configuration_CCL.offset ...
                Configuration_CCL.y ...
                Configuration_CCL.x + k * Configuration_CCL.offset + Configuration_CCL.w ...
                Configuration_CCL.y + Configuration_CCL.h]);
            set_param([ModelName '/OutputScope'],'NumInputPorts','2')            
            set_param([ModelName '/OutputScope'],'ShowLegend','on')
            
            add_line(ModelName,'TFPlant/1','OutputScope/1',...
                'autorouting','on');
            add_line(ModelName,'TFPlant/1','Discriminator/2',...
                'autorouting','on');
            add_line(ModelName,'MPSwitch/1','OutputScope/2',...
                'autorouting','on');
        end
    end
end

