classdef Configuration_SF < IModelConfiguration
    %CONFIGURATION_SF Configuration to generate the model of the
    %system,described by only one transfer function
    %   Detailed explanation goes here
    
    properties (Constant)
        Name = ["System Function" "Configuration_SF"];
        x = 30
        y = 150
        w = 30
        h = 30
        offset = 100
    end
    
    methods (Static)
        function generate(ModelName,TFPlant,TFController)
            %GENERATE Summary of this method goes here
            %   Detailed explanation goes here
            %(x,y) - top left corner of the block
            %(x+w,y+h) - lower right corner of the block
            
            TFOpenLoop = TFPlant*TFController;
            TFClosedLoop = feedback(TFOpenLoop,1);
            
            %Step
            source = 'simulink/Sources/Step';
            dest = [ModelName '/Step'];
            k=0;
            add_block(source, dest,'Position',...
                [Configuration_SF.x ...
                Configuration_SF.y ...
                Configuration_SF.x + Configuration_SF.w ...
                Configuration_SF.y + Configuration_SF.h]);
            
            %Ramp
            source = 'simulink/Sources/Ramp';
            dest = [ModelName '/Ramp'];
            k = k + 1;
            add_block(source, dest,'Position',...
                [Configuration_SF.x ...
                Configuration_SF.y + k * Configuration_SF.offset...
                Configuration_SF.x + Configuration_SF.w ...
                Configuration_SF.y + k * Configuration_SF.offset + Configuration_SF.h]);
            
            %Integrator
            source = 'simulink/Continuous/Integrator';
            dest = [ModelName '/RampIntegrator'];
            add_block(source, dest,'Position',...
                [Configuration_SF.x + Configuration_SF.offset ...
                Configuration_SF.y + Configuration_SF.offset...
                Configuration_SF.x + Configuration_SF.offset + Configuration_SF.w ...
                Configuration_SF.y + Configuration_SF.offset + Configuration_SF.h]);
            
            add_line(ModelName,'Ramp/1','RampIntegrator/1',...
                'autorouting','on');
            
            %Switch key
            source = 'simulink/Sources/Constant';
            dest = [ModelName '/SwitchKey'];
            add_block(source, dest,'Position',...
                [Configuration_SF.x + Configuration_SF.offset ...
                Configuration_SF.y - Configuration_SF.offset...
                Configuration_SF.x + Configuration_SF.offset + Configuration_SF.w ...
                Configuration_SF.y - Configuration_SF.offset + Configuration_SF.h]);
            
            %Multiport switch
            source = 'simulink/Signal Routing/Multiport Switch';
            dest = [ModelName '/MPSwitch'];
            k = k + 1;
            add_block(source, dest,'Position',...
                [Configuration_SF.x + k * Configuration_SF.offset ...
                Configuration_SF.y ...
                Configuration_SF.x + k * Configuration_SF.offset + Configuration_SF.w ...
                Configuration_SF.y + k * Configuration_SF.h]);
            
            add_line(ModelName,'Step/1','MPSwitch/2',...
                'autorouting','on');
            add_line(ModelName,'Ramp/1','MPSwitch/3',...
                'autorouting','on');
            add_line(ModelName,'RampIntegrator/1','MPSwitch/4',...
                'autorouting','on');
            add_line(ModelName,'SwitchKey/1','MPSwitch/1',...
                'autorouting','on');
            
            %Sum
            source = 'built-in/Sum';
            dest = [ModelName '/Discriminator'];
            k = k + 1;
            add_block(source, dest,'Position',...
                [Configuration_SF.x + k * Configuration_SF.offset ...
                Configuration_SF.y ...
                Configuration_SF.x + k * Configuration_SF.offset + Configuration_SF.w ...
                Configuration_SF.y + Configuration_SF.h]);
            set_param([ModelName '/Discriminator'],'Inputs','+-');
            
            add_line(ModelName,'MPSwitch/1','Discriminator/1',...
                'autorouting','on');
            
            %TFClosedLoop
            source = 'simulink/Continuous/Transfer Fcn';
            dest = [ModelName '/TFClosedLoop'];
            add_block(source, dest, 'Position',...
                [Configuration_SF.x + k * Configuration_SF.offset ...
                Configuration_SF.y + Configuration_SF.offset ...
                Configuration_SF.x + k * Configuration_SF.offset + Configuration_SF.w ...
                Configuration_SF.y + Configuration_SF.offset + Configuration_SF.h]);
            set_param(dest,'Numerator',...
                ['[' num2str(TFClosedLoop.num{1}) ']']);
            set_param(dest,'Denominator',...
                ['[' num2str(TFClosedLoop.den{1}) ']']);
            
            add_line(ModelName,'MPSwitch/1','TFClosedLoop/1',...
                'autorouting','on');
            
            %TFOpenLoop
            source = 'simulink/Continuous/Transfer Fcn';
            dest = [ModelName '/TFOpenLoop'];
            k = k + 1;
            add_block(source, dest, 'Position',...
                [Configuration_SF.x + k * Configuration_SF.offset ...
                Configuration_SF.y ...
                Configuration_SF.x + k * Configuration_SF.offset + Configuration_SF.w ...
                Configuration_SF.y + Configuration_SF.h]);
            set_param(dest,'Numerator',...
                ['[' num2str(TFOpenLoop.num{1}) ']']);
            set_param(dest,'Denominator',...
                ['[' num2str(TFOpenLoop.den{1}) ']']);
            
            add_line(ModelName,'Discriminator/1','TFOpenLoop/1',...
                'autorouting','on');
            
            %Error Scope
            source = 'simulink/Sinks/Scope';
            dest = [ModelName '/ErrorScope'];
            add_block(source, dest, 'Position',...
                [Configuration_SF.x + k * Configuration_SF.offset ...
                Configuration_SF.y - Configuration_SF.offset...
                Configuration_SF.x + k * Configuration_SF.offset + Configuration_SF.w ...
                Configuration_SF.y - Configuration_SF.offset + Configuration_SF.h]);
            
            add_line(ModelName,'Discriminator/1','ErrorScope/1',...
                'autorouting','on');
            
            %Out Scope
            source = 'simulink/Sinks/Scope';
            dest = [ModelName '/OutputScope'];
            k = k + 1;
            add_block(source, dest, 'Position',...
                [Configuration_SF.x + k * Configuration_SF.offset ...
                Configuration_SF.y ...
                Configuration_SF.x + k * Configuration_SF.offset + Configuration_SF.w ...
                Configuration_SF.y + Configuration_SF.h]);
            set_param([ModelName '/OutputScope'],'NumInputPorts','3')
            set_param([ModelName '/OutputScope'],'ShowLegend','on')
            
            add_line(ModelName,'TFOpenLoop/1','OutputScope/1',...
                'autorouting','on');
            add_line(ModelName,'TFOpenLoop/1','Discriminator/2',...
                'autorouting','on');
            add_line(ModelName,'MPSwitch/1','OutputScope/2',...
                'autorouting','on');
            add_line(ModelName,'TFClosedLoop/1','OutputScope/3',...
                'autorouting','on');
        end
    end
end

